# Add ~/bin to $PATH if it exists
if [ -e ~/bin ]
then
	PATH="$HOME/bin:$PATH"
fi

if [ -e ~/.cabal/bin ]
then
	PATH="$HOME/.cabal/bin:$PATH"
fi

if [ -e /usr/local/Cellar/smlnj/110.75/libexec/bin ]
then
	PATH="/usr/local/Cellar/smlnj/110.75/libexec/bin:$PATH"
fi

if [ -e /usr/local/share/python ]
then
	PATH="/usr/local/share/python:$PATH"
fi

# shadow system paths with homebrew paths
PATH="/usr/local/bin:/usr/local/sbin:$PATH"

# virtualenvwrapper configuration
# put virtualenvs into
export WORKON_HOME="$HOME/.virtualenv/envs"
# lookup hooks in
export VIRTUALENVWRAPPER_HOOK_DIR="$HOME/.virtualenv/hooks"

# pip configuration
# install into virtualenv per default
export PIP_RESPECT_VIRTUALENV=true
# use the same directory as virtualenvwrapper for virtualenvs
export PIP_VIRTUALENV_BASE=$WORKON_HOME
export PIP_DOWNLOAD_CACHE=$HOME/.pip_download_cache

export LC_ALL=en_GB.UTF-8
export LANG=en_GB.UTF-8
