# path to configuration
ZSH=~/.zsh
ZSH_THEME="dasich"

# initialize configuration
source $ZSH/init.sh

# initialize virtualenvwrapper
if [ -e /usr/local/bin/virtualenvwrapper.sh ]
then
  source /usr/local/bin/virtualenvwrapper.sh
fi
