# path to configuration
ZSH=~/.zsh
ZSH_THEME="dasich"

# initialize configuration
source $ZSH/init.sh

# initialize virtualenvwrapper
if [ -e /usr/local/bin/virtualenvwrapper.sh ]
then
  source /usr/local/bin/virtualenvwrapper.sh
fi

# when cd-ing automatically activate the virtualenv corresponding to the
# current directory if possible
auto_workon () {
  cd "$@"
  workon $(basename `pwd`) &> /dev/null
}

alias cd="auto_workon"
